In [3]:
# GOAL :: partitioning X heritability

In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import sys
import sys; sys.path.append("/data/jerrylee/pjt/BIGFAM.v.0.1")

from BIGFAM import obj2, tools
import importlib

In [2]:
source = "GS"

# Step 1. Load data

In [3]:
# load FR-reg
frreg_path = f"/data/jerrylee/pjt/BIGFAM.v.0.1/data/{source}/frreg/REL"
fns = os.listdir(frreg_path)
len(fns)

32

# Step 2. Estimate X

In [4]:
output_path = f"/data/jerrylee/pjt/BIGFAM.v.0.1/data/{source}/obj2"

## Step 2.1. X in all

In [24]:
df = pd.DataFrame(
    columns=[
        "pheno", "lambda", "weight", 
        "Vx", "lower_Vx", "upper_Vx"
    ]
)

for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        for weight in range(-2, 9):
            df_x = obj2.estimateX(
                df_frreg,
                n_resample=100,
                regout_bin=["DOR"],
                alpha_dicts={"type": "lambda", "weight":weight},)
        
            df.loc[len(df)] = [
                pheno, df_x["lambda"].mean(), weight,
                np.median(df_x["X"]), np.percentile(df_x["X"], 2.5), 
                np.percentile(df_x["X"], 97.5)
            ]
    except:
        print(fn)
    break

  0%|          | 0/32 [00:00<?, ?it/s]

[1/32] avg_dia

  3%|▎         | 1/32 [00:25<13:09, 25.46s/it]

[2/32] max_leg

  6%|▋         | 2/32 [00:50<12:45, 25.51s/it]

[3/32] avg_hr

  9%|▉         | 3/32 [01:16<12:19, 25.50s/it]

[4/32] avg_sys

 12%|█▎        | 4/32 [01:42<11:54, 25.52s/it]

[5/32] PR_interval

 16%|█▌        | 5/32 [02:07<11:29, 25.54s/it]

[6/32] Glucose

 19%|█▉        | 6/32 [02:33<11:11, 25.83s/it]

[7/32] HDL_cholesterol

 22%|██▏       | 7/32 [02:59<10:44, 25.79s/it]

[8/32] Total_cholesterol

 25%|██▌       | 8/32 [03:25<10:16, 25.70s/it]

[9/32] QT_interval

 28%|██▊       | 9/32 [03:50<09:50, 25.67s/it]

[10/32] Sodium

 31%|███▏      | 10/32 [04:16<09:24, 25.65s/it]

[11/32] FEV

 34%|███▍      | 11/32 [04:41<08:57, 25.61s/it]

[12/32] QRS_axis

 38%|███▊      | 12/32 [05:07<08:30, 25.52s/it]

[13/32] Heart_Rate

 41%|████      | 13/32 [05:32<08:04, 25.51s/it]

[14/32] max_arm

 44%|████▍     | 14/32 [05:58<07:39, 25.53s/it]

[15/32] ratio

 47%|████▋     | 15/32 [06:23<07:13, 25.50s/it]

[16/32] Creat_mgdl

 50%|█████     | 16/32 [06:49<06:48, 25.55s/it]

[17/32] max_sys

 53%|█████▎    | 17/32 [07:14<06:23, 25.55s/it]

[18/32] Potassium

 56%|█████▋    | 18/32 [07:40<05:57, 25.56s/it]

[19/32] FVC

 59%|█████▉    | 19/32 [08:06<05:32, 25.59s/it]

[20/32] abpi

 62%|██████▎   | 20/32 [08:36<05:22, 26.90s/it]

[21/32] FEF

 66%|██████▌   | 21/32 [09:01<04:51, 26.51s/it]

[22/32] ECG_Count

 69%|██████▉   | 22/32 [09:27<04:23, 26.33s/it]

[23/32] LVMI_Rautaharju

 72%|███████▏  | 23/32 [09:55<04:01, 26.84s/it]

[24/32] QRS_duration

 75%|███████▌  | 24/32 [10:23<03:36, 27.06s/it]

[25/32] T_axis

 78%|███████▊  | 25/32 [10:48<03:06, 26.63s/it]

[26/32] QTC_interval

 81%|████████▏ | 26/32 [11:15<02:40, 26.73s/it]

[27/32] Urea

 84%|████████▍ | 27/32 [11:41<02:12, 26.42s/it]

[28/32] P_duration

 88%|████████▊ | 28/32 [12:07<01:44, 26.22s/it]

[29/32] LVMI_Fhuwez

 91%|█████████ | 29/32 [12:35<01:19, 26.66s/it]

[30/32] Creatinine

 94%|█████████▍| 30/32 [13:00<00:52, 26.39s/it]

[31/32] expected

 97%|█████████▋| 31/32 [13:26<00:26, 26.23s/it]

[32/32] P_axis

100%|██████████| 32/32 [13:52<00:00, 26.02s/it]

In [27]:
df.to_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/obj2/X.tsv",
    sep='\t',
    index=False
)

In [15]:
for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        df_x = obj2.estimateX(df_frreg,
                            n_resample=100,
                            alpha_dicts={"type": "eta", "weight":1},
                            regout_bin=["DOR", "sex_type"])
        if df_x.shape[0] > 0:
            # save raw results
            df_x.to_csv(f"{output_path}/{pheno}.X_raw",
                        sep='\t',
                        index=False)
            tools.raw2long(df_x, params=["eta", "alpha", "X"]).to_csv(
                f"{output_path}/{pheno}.X",
                sep='\t',
                index=False)
    except:
        print(fn)

  0%|          | 0/32 [00:00<?, ?it/s]

[1/32] avg_dia

  0%|          | 0/32 [00:04<?, ?it/s]

## Step 2.2 X in male and female

In [16]:
df = pd.DataFrame(
    columns=[
        "pheno", "Vg", "weight", 
        "xMale", "lower_xMale", "upper_xMale",
        "xFemale", "lower_xFemale", "upper_xFemale",
        "r", "lower_r", "upper_r"
    ]
)

for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        for weight in range(-2, 9):
            df_xmxf = obj2.estimateXmXfR(
                df_frreg,
                n_resample=100,
                alpha_dicts={"type": "eta", "weight":weight},
                regout_bin=["DOR", "sex_type"]
            )
            
            df.loc[len(df)] = [
                pheno, df_xmxf["eta"].mean(), weight,
                np.median(df_xmxf["Xmale"]), np.percentile(df_xmxf["Xmale"], 2.5), 
                np.percentile(df_xmxf["Xmale"], 97.5),
                np.median(df_xmxf["Xfemale"]), np.percentile(df_xmxf["Xfemale"], 2.5), 
                np.percentile(df_xmxf["Xfemale"], 97.5),
                np.median(df_xmxf["r"]), np.percentile(df_xmxf["r"], 2.5), np.percentile(df_xmxf["r"], 97.5),
            ]
    except:
        print(fn)

  0%|          | 0/32 [00:00<?, ?it/s]

[1/32] avg_dia

  3%|▎         | 1/32 [00:54<28:03, 54.32s/it]

[2/32] max_leg

  6%|▋         | 2/32 [01:44<26:03, 52.10s/it]

[3/32] avg_hr

  9%|▉         | 3/32 [02:40<25:53, 53.57s/it]

[4/32] avg_sys

 12%|█▎        | 4/32 [03:37<25:41, 55.06s/it]

[5/32] PR_interval

 16%|█▌        | 5/32 [04:34<25:05, 55.77s/it]

[6/32] Glucose

 19%|█▉        | 6/32 [05:44<26:13, 60.52s/it]

[7/32] HDL_cholesterol

 22%|██▏       | 7/32 [06:40<24:34, 58.97s/it]

[8/32] Total_cholesterol

 25%|██▌       | 8/32 [07:41<23:50, 59.60s/it]

[9/32] QT_interval

 28%|██▊       | 9/32 [08:39<22:43, 59.29s/it]

[10/32] Sodium

 31%|███▏      | 10/32 [09:33<21:05, 57.54s/it]

[11/32] FEV

 34%|███▍      | 11/32 [10:26<19:38, 56.13s/it]

[12/32] QRS_axis

 38%|███▊      | 12/32 [11:20<18:32, 55.63s/it]

[13/32] Heart_Rate

 41%|████      | 13/32 [12:12<17:14, 54.47s/it]

[14/32] max_arm

 44%|████▍     | 14/32 [13:06<16:15, 54.22s/it]

[15/32] ratio

 47%|████▋     | 15/32 [14:06<15:51, 55.97s/it]

[16/32] Creat_mgdl

 50%|█████     | 16/32 [14:58<14:39, 54.97s/it]

[17/32] max_sys

 53%|█████▎    | 17/32 [15:53<13:42, 54.86s/it]

[18/32] Potassium

 56%|█████▋    | 18/32 [17:06<14:03, 60.27s/it]

[19/32] FVC

 59%|█████▉    | 19/32 [17:59<12:37, 58.28s/it]

[20/32] abpi

 62%|██████▎   | 20/32 [19:11<12:27, 62.29s/it]

[21/32] FEF

 66%|██████▌   | 21/32 [20:00<10:42, 58.41s/it]

[22/32] ECG_Count

 69%|██████▉   | 22/32 [20:50<09:17, 55.79s/it]

[23/32] LVMI_Rautaharju

 72%|███████▏  | 23/32 [21:47<08:24, 56.07s/it]

[24/32] QRS_duration

 75%|███████▌  | 24/32 [22:50<07:46, 58.28s/it]

[25/32] T_axis

 78%|███████▊  | 25/32 [24:24<08:02, 68.87s/it]

[26/32] QTC_interval

 81%|████████▏ | 26/32 [25:24<06:37, 66.30s/it]

[27/32] Urea

 84%|████████▍ | 27/32 [26:23<05:20, 64.13s/it]

[28/32] P_duration

 88%|████████▊ | 28/32 [27:11<03:56, 59.14s/it]

[29/32] LVMI_Fhuwez

 91%|█████████ | 29/32 [28:17<03:03, 61.18s/it]

[30/32] Creatinine

 94%|█████████▍| 30/32 [29:12<01:58, 59.48s/it]

[31/32] expected

 97%|█████████▋| 31/32 [30:25<01:03, 63.59s/it]

[32/32] P_axis

100%|██████████| 32/32 [31:22<00:00, 58.83s/it]

In [17]:
df

,pheno,Vg,weight,xMale,lower_xMale,upper_xMale,xFemale,lower_xFemale,upper_xFemale,r,lower_r,upper_r
0,avg_dia,0.462170,-2,0.170508,0.119892,0.227544,0.058049,0.014920,0.115315,-0.5,-1.000,0.600
1,max_leg,0.577093,-2,0.048187,0.003188,0.105692,0.028363,0.001603,0.062078,1.0,-1.000,1.000
2,avg_hr,0.488948,-2,0.059629,0.014652,0.131566,0.024964,0.001029,0.059627,-1.0,-1.000,1.000
3,avg_sys,0.351970,-2,0.178177,0.097446,0.258600,0.044576,0.005581,0.118571,1.0,-0.105,1.000
4,PR_interval,2.896398,-2,0.000554,0.000001,0.003294,0.001825,0.000607,0.003307,-1.0,-1.000,1.000
5,Glucose,0.293378,-2,0.044744,0.003182,0.126357,0.010515,0.000001,0.057821,1.0,-1.000,1.000
6,HDL_cholesterol,0.624631,-2,0.033345,0.000156,0.083784,0.016024,0.000840,0.038763,-0.1,-1.000,1.000
7,Total_cholesterol,0.444719,-2,0.152093,0.082295,0.256005,0.080694,0.048493,0.133083,-0.6,-1.000,0.200
8,QT_interval,0.378232,-2,0.109588,0.030704,0.175677,0.074280,0.021737,0.128745,0.0,-1.000,1.000
9,Sodium,1.055726,-2,0.017322,0.000887,0.039414,0.016186,0.003855,0.027708,-1.0,-1.000,-1.000
10,FEV,0.609521,-2,0.023596,0.000228,0.057283,0.031885,0.011654,0.060517,-1.0,-1.000,1.000
11,QRS_axis,0.460617,-2,0.170561,0.094949,0.309956,0.037370,0.003718,0.076180,1.0,-0.705,1.000
12,Heart_Rate,0.435645,-2,0.067087,0.020613,0.112338,0.043778,0.010833,0.093973,-1.0,-1.000,0.525
13,max_arm,0.480859,-2,0.130238,0.070523,0.196773,0.042056,0.004849,0.086175,1.0,0.095,1.000
14,ratio,0.340984,-2,0.080616,0.023694,0.143954,0.073492,0.027811,0.163728,-1.0,-1.000,0.800
15,Creat_mgdl,0.950509,-2,0.015326,0.003570,0.029110,0.014466,0.004303,0.026094,-0.4,-1.000,1.000
16,max_sys,0.443827,-2,0.146631,0.078262,0.229630,0.044767,0.013509,0.095024,0.4,-1.000,1.000
17,Potassium,0.379770,-2,0.071649,0.011957,0.133292,0.018047,0.000039,0.070215,-1.0,-1.000,1.000
18,FVC,0.705764,-2,0.034908,0.010240,0.063026,0.052028,0.033553,0.078929,-1.0,-1.000,1.000
19,abpi,0.319144,-2,0.041937,0.000001,0.151441,0.002530,0.000001,0.037514,1.0,-1.000,1.000
20,FEF,0.467749,-2,0.016243,0.000001,0.049322,0.010160,0.000001,0.057514,-1.0,-1.000,1.000
21,ECG_Count,4.138264,-2,0.000519,0.000001,0.001739,0.000990,0.000544,0.001456,1.0,-1.000,1.000
22,LVMI_Rautaharju,0.375877,-2,0.055004,0.006948,0.099839,0.062757,0.009755,0.133112,-1.0,-1.000,0.105
23,QRS_duration,0.266514,-2,0.165559,0.087811,0.256681,0.117329,0.007153,0.226694,-0.8,-1.000,0.400
24,T_axis,0.473116,-2,0.000242,0.000001,0.027479,0.048179,0.012916,0.119895,1.0,-1.000,1.000
25,QTC_interval,0.395198,-2,0.038454,0.001614,0.107947,0.072033,0.028078,0.130771,1.0,0.095,1.000
26,Urea,0.380213,-2,0.015080,0.000001,0.072045,0.037429,0.000001,0.103152,-1.0,-1.000,-0.895
27,P_duration,3.453245,-2,0.000813,0.000001,0.002563,0.000833,0.000001,0.001716,-1.0,-1.000,1.000
28,LVMI_Fhuwez,0.363251,-2,0.000013,0.000001,0.028338,0.000901,0.000001,0.042649,0.9,-1.000,1.000
29,Creatinine,0.973725,-2,0.012779,0.001019,0.029195,0.013627,0.004658,0.023832,-1.0,-1.000,1.000
30,expected,1.085671,-2,0.003693,0.000078,0.013771,0.036013,0.025161,0.048485,-1.0,-1.000,1.000
31,P_axis,2.769254,-2,0.002078,0.000001,0.004668,0.000041,0.000001,0.001954,1.0,-1.000,1.000

In [8]:
for idx in sorted(df_xmxf["block_idx"].unique()):
    tmp = df_xmxf[df_xmxf["block_idx"] == idx].copy()
    
    break
tmp
# eta = np.mean(df_ukb[(df_ukb["pheno"] == pheno)]["eta"])
# df_ukb_formatted.loc[len(df_ukb_formatted)] = [
#     pheno, -weight, eta,
#     tmp["Xmale"].values[0], tmp["lower_Xmale"].values[0], tmp["upper_Xmale"].values[0],
#     tmp["Xfemale"].values[0], tmp["lower_Xfemale"].values[0], tmp["upper_Xfemale"].values[0],
# ]

    block_idx       eta     alpha     Xmale   Xfemale    r  func_val
0         0.0  0.453094  4.871052  0.011506  0.005475 -1.0  0.060510
1         0.0  0.453094  4.871052  0.011320  0.005152 -0.8  0.060552
2         0.0  0.453094  4.871052  0.011133  0.004795 -0.6  0.060593
3         0.0  0.453094  4.871052  0.010944  0.004413 -0.4  0.060633
4         0.0  0.453094  4.871052  0.010759  0.003990 -0.2  0.060672
5         0.0  0.453094  4.871052  0.010584  0.003512  0.0  0.060709
6         0.0  0.453094  4.871052  0.010581  0.000001  0.2  0.060770
7         0.0  0.453094  4.871052  0.010578  0.000001  0.4  0.060770
8         0.0  0.453094  4.871052  0.010576  0.000001  0.6  0.060771
9         0.0  0.453094  4.871052  0.010573  0.000001  0.8  0.060772
10        0.0  0.453094  4.871052  0.010579  0.000001  1.0  0.060772

In [9]:
tmp[tmp["func_val"] == tmp["func_val"].min()]

   block_idx       eta     alpha     Xmale   Xfemale    r  func_val
0        0.0  0.453094  4.871052  0.011506  0.005475 -1.0   0.06051

In [4]:
df = pd.DataFrame(
    columns=[
        "pheno", "Vg", "weight", 
        "xMale", "lower_xMale", "upper_xMale",
        "xFemale", "lower_xFemale", "upper_xFemale",
        "r", "lower_r", "upper_r"
    ]
)

for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        for weight in range(-2, 9):
            df_xmxf = obj2.estimateXmXf(
                df_frreg,
                n_resample=100,
                alpha_dicts={"type": "eta", "weight":weight},
                regout_bin=["DOR", "sex_type"]
            )
            
            df.loc[len(df)] = [
                pheno, df_xmxf["eta"].mean(), weight,
                np.median(df_xmxf["Xmale"]), np.percentile(df_xmxf["Xmale"], 2.5), 
                np.percentile(df_xmxf["Xmale"], 97.5),
                np.median(df_xmxf["Xfemale"]), np.percentile(df_xmxf["Xfemale"], 2.5), 
                np.percentile(df_xmxf["Xfemale"], 97.5),
            ]
    except:
        print(fn)
    break

  0%|          | 0/106 [00:00<?, ?it/s]

[1/106] Weight

  0%|          | 0/106 [01:24<?, ?it/s]

In [11]:
df_frreg

,DOR,relationship,sex_type,Erx,slope,se,p,n
0,1,DS,FF,0.750000,0.288782,0.012384,3.420132e-115,5978
1,1,FD,FM,0.707107,0.301651,0.022592,7.919335e-39,1782
2,1,FS,MM,0.000000,0.249942,0.028223,2.994043e-18,1178
3,1,MD,FF,0.500000,0.311197,0.015980,2.513532e-80,3538
4,1,MS,FM,0.707107,0.299455,0.019319,9.363333e-52,2440
5,1,SB,MM,0.500000,0.330456,0.026432,6.481882e-34,1276
6,1,SS_DB,FM,0.353553,0.272642,0.016159,1.699636e-61,3546
7,2,DFB,FM,0.353553,0.214419,0.042228,5.285389e-07,536
8,2,DFS,FF,0.250000,0.179490,0.039996,8.617515e-06,606
9,2,DMB,FM,0.176777,0.041381,0.048580,3.948058e-01,424
10,2,DMS,FF,0.375000,0.114994,0.030157,1.449553e-04,1086
11,2,SFB,MM,0.000000,0.102208,0.029980,6.750464e-04,1102
12,2,SMB,MM,0.250000,0.159595,0.073377,3.092642e-02,182
13,2,SMS,FM,0.530330,0.106990,0.039332,6.702359e-03,640
14,3,DFBD_DMBD,FF,0.250000,0.122615,0.023690,2.530764e-07,1756
15,3,DFSD,FF,0.125000,0.073021,0.023672,2.069381e-03,1776
16,3,DMSD,FF,0.187500,0.072468,0.020270,3.569588e-04,2422
17,3,SFBD_SFSD_DFBS_DMBS,FM,0.000000,0.075124,0.009399,1.442880e-15,11258
18,3,SFBS_SFSS_SMBS,MM,0.000000,0.096494,0.012545,1.673306e-14,6296
19,3,SMBD_DFSS,FM,0.176777,0.064508,0.023593,6.315433e-03,1790
20,3,SMSD_DMSS,FM,0.265165,0.091123,0.022442,5.092210e-05,1970
21,3,SMSS,MM,0.375000,0.168903,0.042692,8.642814e-05,534

In [33]:
df.to_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/obj2/XmXf.tsv",
    sep='\t',
    index=False
)

In [35]:
df.groupby("weight").mean()

,Vg,xMale,lower_xMale,upper_xMale,xFemale,lower_xFemale,upper_xFemale
weight,,,,,,,
-2,0.514621,0.074544,0.029515,0.137777,0.042192,0.008468,0.095078
-1,0.514621,0.042162,0.016093,0.079449,0.018711,0.004222,0.039667
0,0.514621,0.017105,0.006368,0.036139,0.007968,0.002287,0.015907
1,0.514621,0.006514,0.001539,0.016662,0.004800,0.001634,0.008896
2,0.514621,0.003116,0.000563,0.011925,0.004383,0.001506,0.007895
3,0.514621,0.003419,0.000154,0.012345,0.005375,0.001944,0.009355
4,0.514621,0.003157,0.000042,0.014962,0.007363,0.002995,0.013288
5,0.514621,0.004042,0.000014,0.018978,0.010571,0.004630,0.020927
6,0.514621,0.005912,0.000004,0.024275,0.016454,0.006765,0.030030
7,0.514621,0.007412,0.000054,0.031717,0.024651,0.011649,0.042760
8,0.514621,0.007479,0.000002,0.031179,0.033793,0.014331,0.051109

In [10]:
for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        df_x = obj2.estimateXmXf(df_frreg,
                                alpha_dicts={"type": "eta", "weight":-1})
        if df_x.shape[0] > 0:
            # save raw results
            df_x.to_csv(f"{output_path}/{pheno}.XmXf_raw",
                        sep='\t',
                        index=False)
            df_x_sums = tools.raw2long(df_x, params=["eta", "alpha", "Xmale", "Xfemale"])
            
            df_x_sums.to_csv(
                f"{output_path}/{pheno}.XmXf",
                sep='\t',
                index=False)
            
            print(pheno)
            print(df_x_sums)
    except:
        print(fn)

  0%|          | 0/40 [00:00<?, ?it/s]

[1/40] avg_dia

  2%|▎         | 1/40 [00:08<05:21,  8.25s/it]

avg_dia
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.405472     0.309200      0.488235
1    alpha  6.082666     4.195347     10.463819
2    Xmale  0.011217     0.004321      0.020573
3  Xfemale  0.000001     0.000001      0.001640
[2/40] height
height.REL.frreg
[3/40] weight
weight.REL.frreg
[4/40] max_leg

 10%|█         | 4/40 [00:16<02:13,  3.72s/it]

max_leg
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.459526     0.365125      0.560112
1    alpha  4.735675     3.187647      7.501499
2    Xmale  0.009158     0.000001      0.021741
3  Xfemale  0.000001     0.000001      0.008461
[5/40] avg_hr

 12%|█▎        | 5/40 [00:24<02:51,  4.89s/it]

avg_hr
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.495084     0.391287      0.585545
1    alpha  4.079834     2.921170      6.533845
2    Xmale  0.000001     0.000001      0.008602
3  Xfemale  0.010505     0.000730      0.020091
[6/40] avg_sys

 15%|█▌        | 6/40 [00:32<03:16,  5.79s/it]

avg_sys
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.417563     0.324864      0.519276
1    alpha  5.735412     3.708615      9.475406
2    Xmale  0.009598     0.002702      0.019490
3  Xfemale  0.000001     0.000001      0.003256
[7/40] PR_interval

 18%|█▊        | 7/40 [00:39<03:25,  6.24s/it]

PR_interval
     param    median  lower(2.5%)  upper(97.5%)
0      eta  1.530961     1.444382      1.605917
1    alpha  0.426650     0.387759      0.479332
2    Xmale  0.381593     0.338735      0.443841
3  Xfemale  0.000001     0.000001      0.000001
[8/40] Glucose

 20%|██        | 8/40 [00:46<03:29,  6.54s/it]

Glucose
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.238612     0.133502      0.321852
1    alpha  17.565600     9.653548     56.130854
2    Xmale   0.000163     0.000001      0.002549
3  Xfemale   0.001230     0.000001      0.005178
[9/40] HDL_cholesterol

 22%|██▎       | 9/40 [00:54<03:35,  6.95s/it]

HDL_cholesterol
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.695786     0.600398      0.796534
1    alpha  2.065627     1.576469      2.774110
2    Xmale  0.000001     0.000001      0.009806
3  Xfemale  0.012630     0.000001      0.035610
[10/40] Total_cholesterol

 25%|██▌       | 10/40 [01:03<03:42,  7.42s/it]

Total_cholesterol
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.405529     0.299347      0.521344
1    alpha  6.080862     3.682936     11.161152
2    Xmale  0.014475     0.005602      0.024837
3  Xfemale  0.000460     0.000001      0.008168
[11/40] QT_interval

 28%|██▊       | 11/40 [01:10<03:37,  7.50s/it]

QT_interval
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.343992     0.259239      0.440500
1    alpha  8.450904     5.153568     14.926689
2    Xmale  0.005184     0.000655      0.012377
3  Xfemale  0.000001     0.000001      0.002510
[12/40] Sodium

 30%|███       | 12/40 [01:18<03:29,  7.47s/it]

Sodium
     param    median  lower(2.5%)  upper(97.5%)
0      eta  1.041053     0.948724      1.125377
1    alpha  0.922689     0.789602      1.111064
2    Xmale  0.008230     0.000001      0.036250
3  Xfemale  0.000001     0.000001      0.025080
[13/40] FEV

 32%|███▎      | 13/40 [01:25<03:20,  7.44s/it]

FEV
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.619956     0.516424      0.716063
1    alpha  2.601911     1.950505      3.761774
2    Xmale  0.000001     0.000001      0.008559
3  Xfemale  0.004870     0.000001      0.022465
[14/40] QRS_axis

 35%|███▌      | 14/40 [01:34<03:20,  7.72s/it]

QRS_axis
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.286981     0.198547      0.378609
1    alpha  12.142996     6.976193     25.369840
2    Xmale   0.012413     0.005776      0.021520
3  Xfemale   0.000001     0.000001      0.000348
[15/40] absi
absi.REL.frreg
[16/40] Heart_Rate

 40%|████      | 16/40 [01:41<02:21,  5.88s/it]

Heart_Rate
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.402568     0.294995      0.492717
1    alpha  6.170678     4.119626     11.491508
2    Xmale  0.002599     0.000001      0.011657
3  Xfemale  0.000614     0.000001      0.007383
[17/40] max_arm

 42%|████▎     | 17/40 [01:49<02:29,  6.50s/it]

max_arm
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.451221     0.347003      0.569439
1    alpha  4.911633     3.083942      8.308785
2    Xmale  0.014430     0.005490      0.027167
3  Xfemale  0.000001     0.000001      0.008486
[18/40] ratio

 45%|████▌     | 18/40 [01:57<02:29,  6.82s/it]

ratio
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.374079     0.263400      0.482418
1    alpha  7.146199     4.297346     14.573871
2    Xmale  0.003436     0.000001      0.011054
3  Xfemale  0.006461     0.000658      0.014762
[19/40] hips
hips.REL.frreg
[20/40] Creat_mgdl

 50%|█████     | 20/40 [02:04<01:47,  5.37s/it]

Creat_mgdl
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.936221     0.850894      1.025238
1    alpha  1.140896     0.951418      1.381184
2    Xmale  0.000001     0.000001      0.000001
3  Xfemale  0.000001     0.000001      0.022775
[21/40] max_sys

 52%|█████▎    | 21/40 [02:12<01:54,  6.05s/it]

max_sys
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.430613     0.332050      0.538209
1    alpha  5.393453     3.452942      9.069740
2    Xmale  0.011704     0.004327      0.020182
3  Xfemale  0.000001     0.000001      0.005296
[22/40] Potassium

 55%|█████▌    | 22/40 [02:19<01:53,  6.33s/it]

Potassium
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.325715     0.215050      0.419886
1    alpha  9.426330     5.680584     21.640837
2    Xmale  0.000001     0.000001      0.003633
3  Xfemale  0.000261     0.000001      0.005079
[23/40] FVC

 57%|█████▊    | 23/40 [02:28<01:56,  6.86s/it]

FVC
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.838398     0.727891      0.936535
1    alpha  1.422655     1.140124      1.887423
2    Xmale  0.005776     0.000001      0.037759
3  Xfemale  0.032978     0.004678      0.052524
[24/40] abpi

 60%|██████    | 24/40 [02:35<01:51,  6.98s/it]

abpi
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.139691     0.020941      0.234659
1    alpha  51.248026    18.224526   2025.333716
2    Xmale   0.000454     0.000001      0.002214
3  Xfemale   0.000001     0.000001      0.000611
[25/40] FEF

 62%|██████▎   | 25/40 [02:43<01:46,  7.11s/it]

FEF
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.448100     0.358507      0.559808
1    alpha  4.980243     3.193679      7.781724
2    Xmale  0.000977     0.000001      0.013186
3  Xfemale  0.002546     0.000001      0.008775
[26/40] ECG_Count

 65%|██████▌   | 26/40 [02:50<01:40,  7.21s/it]

ECG_Count
     param    median  lower(2.5%)  upper(97.5%)
0      eta  2.210490     2.141926      2.284547
1    alpha  0.204655     0.191604      0.217967
2    Xmale  0.718088     0.653950      0.795028
3  Xfemale  0.000001     0.000001      0.000001
[27/40] whr
whr.REL.frreg
[28/40] waist
waist.REL.frreg
[29/40] LVMI_Rautaharju

 72%|███████▎  | 29/40 [02:57<00:50,  4.60s/it]

LVMI_Rautaharju
     param      median  lower(2.5%)   upper(97.5%)
0      eta    0.075552     0.000016       0.171830
1    alpha  175.203782    34.029105  222683.649085
2    Xmale    0.000001     0.000001       0.000001
3  Xfemale    0.000182     0.000001       0.001461
[30/40] QRS_duration

 75%|███████▌  | 30/40 [03:05<00:51,  5.17s/it]

QRS_duration
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.178232     0.078935      0.264617
1    alpha  31.479965    14.281873    160.498161
2    Xmale   0.000007     0.000001      0.001673
3  Xfemale   0.000332     0.000001      0.001995
[31/40] T_axis

 78%|███████▊  | 31/40 [03:13<00:52,  5.79s/it]

T_axis
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.219438     0.122911      0.305747
1    alpha  20.767178    10.700224     66.224497
2    Xmale   0.007634     0.002404      0.017280
3  Xfemale   0.000001     0.000001      0.000856
[32/40] QTC_interval

 80%|████████  | 32/40 [03:20<00:49,  6.18s/it]

QTC_interval
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.320057     0.237732      0.387647
1    alpha  9.762404     6.658812     17.693894
2    Xmale  0.001919     0.000001      0.005657
3  Xfemale  0.001265     0.000001      0.007388
[33/40] Urea

 82%|████████▎ | 33/40 [03:27<00:45,  6.47s/it]

Urea
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.245539     0.128314      0.328628
1    alpha  16.586822     9.260287     60.831221
2    Xmale   0.000428     0.000001      0.003744
3  Xfemale   0.000304     0.000001      0.002285
[34/40] P_duration

 85%|████████▌ | 34/40 [03:35<00:40,  6.72s/it]

P_duration
     param    median  lower(2.5%)  upper(97.5%)
0      eta  1.849263     1.784011      1.940441
1    alpha  0.292417     0.265594      0.314199
2    Xmale  0.595249     0.534650      0.656157
3  Xfemale  0.000001     0.000001      0.000001
[35/40] body_fat
body_fat.REL.frreg
[36/40] bmi
bmi.REL.frreg
[37/40] LVMI_Fhuwez

 92%|█████████▎| 37/40 [03:42<00:13,  4.41s/it]

LVMI_Fhuwez
     param     median  lower(2.5%)  upper(97.5%)
0      eta   0.207061     0.115237      0.337056
1    alpha  23.330444     8.803206     75.717023
2    Xmale   0.000001     0.000001      0.001078
3  Xfemale   0.000116     0.000001      0.002136
[38/40] Creatinine

 95%|█████████▌| 38/40 [03:49<00:09,  4.93s/it]

Creatinine
     param    median  lower(2.5%)  upper(97.5%)
0      eta  0.958458     0.883483      1.074497
1    alpha  1.088565     0.866147      1.281340
2    Xmale  0.000001     0.000001      0.000001
3  Xfemale  0.000001     0.000001      0.017732
[39/40] expected

 98%|█████████▊| 39/40 [03:57<00:05,  5.60s/it]

expected
     param    median  lower(2.5%)  upper(97.5%)
0      eta  1.124256     1.052459      1.232076
1    alpha  0.791170     0.658756      0.902796
2    Xmale  0.000001     0.000001      0.012349
3  Xfemale  0.032725     0.000584      0.077800
[40/40] P_axis

100%|██████████| 40/40 [04:04<00:00,  6.12s/it]

P_axis
     param    median  lower(2.5%)  upper(97.5%)
0      eta  1.462106     1.381788      1.524317
1    alpha  0.467781     0.430377      0.523768
2    Xmale  0.460777     0.398042      0.513587
3  Xfemale  0.000001     0.000001      0.000001