In [3]:
import numpy as np
import pandas as pd
import os
import sys
sys.path.append("/data/jerrylee/pjt/BIGFAM.v.0.1/BIGFAM")

import famgen.gen_geno as fgg
import famgen.gen_pheno as fgp
from reml_utils import *

# simulation

In [4]:
# GENOTYPE-related Parameters
num_sample = 100
num_variant = 100
prop_commom_rare = -1 # only common variant (0 for only rare)

In [5]:
# PHENOTYPE related parameters
dc_type = "FDC"
beta = {"autosome" : np.random.normal(0, 1, size=num_variant),
        "chrX" : np.random.normal(0, 1, size=num_variant)}

hsqs = {
    "autosome" : 0.5,
    "chrX" : 0,
    "fam" : 0.05,
    "po" : 0.05,
    "sib" : 0.1,
}

In [6]:
# genotype-related add-hoc functions
def make_parents_haps(class_FamGenoSimul, num_sample):
    """Generate parent haplotypes.

    This function generates the haplotypes for the father and mother. The haplotypes
    are stored in a dictionary with the keys "father" and "mother". Each parent has
    two keys, "autosome" and "chrX".

    Args:
        class_FamGenoSimul (class): The FamGenoSimul class instance.
        num_sample (int): The number of samples to generate.

    Returns:
        dict: A dictionary of the generated parent haplotypes.
    """
    dict_parents = {
        "father" : {
            "autosome" : None,
            "chrX" : None},
        "mother" : {
            "autosome" : None,
            "chrX" : None}
    }

    ## MAKE PARENT's HAPS
    for parent in ["father", "mother"]:
        for chr_type in ["autosome", "chrX"]:
            if (chr_type == "chrX") & (parent == "father"):
                dict_parents[parent][chr_type], _ = class_FamGenoSimul.generate_parent_haplotype(num_sample=num_sample, chr_type="haploid")
            else:
                dict_parents[parent][chr_type], _ = class_FamGenoSimul.generate_parent_haplotype(num_sample=num_sample, chr_type="diploid")
    
    return dict_parents

def make_offspring_haps(class_FamGenoSimul, dict_parents, off_type):
    # off_type = "son", "daughter"
    dict_off = {
        "autosome" : None,
        "chrX" : None
    }
    for chr_type in ["autosome", "chrX"]:
        dict_off[chr_type] = class_FamGenoSimul.make_offspring_haplotype(
            haps_mother = dict_parents["mother"][chr_type],
            haps_father = dict_parents["father"][chr_type],
            off_type = off_type,
            chr_type=chr_type
        )
    return dict_off

def make_family_geno(class_FamGenoSimul, num_sample, rel):
    """
    Generate offspring's genotype for the specified relationship type.
    
    Parameters:
    class_FamGenoSimul (class): Class for family simulation.
    num_sample (int): The number of samples to be simulated.
    rel (str): Relationship type. 
        Options: father_son, mother_son, father_daughter, mother_daughter, son_son, son_daughter, daughter_daughter
        
    Returns:
    dict: Dictionary with offspring's genotype for each chromosome type.
    
    """
    parents = ["father", "mother"]
    offs = ["son", "daughter"]
    pos = ["father_son", "mother_son", "father_daughter", "mother_daughter"]
    sibs = ["son_son", "son_daughter", "daughter_daughter"]
    
    dict_parents = make_parents_haps(class_FamGenoSimul, num_sample)
    
    ## MAKE OFFSPRING's HAPS ##
    if rel in ["father_son", "mother_son"]:
        dict_off = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="son")
        
    elif rel in ["father_daughter", "mother_daughter"]:
        dict_off = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="daughter")

    elif rel == "son_son":
        dict_off1 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="son")
        dict_off2 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="son")

    elif rel == "son_daughter":
        dict_off1 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="son")
        dict_off2 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="daughter")

    elif rel == "daughter_daughter":
        dict_off1 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="daughter")
        dict_off2 = make_offspring_haps(class_FamGenoSimul, dict_parents, off_type="daughter")

    else: 
        raise Exception("!!")

    # return dict_parents
    dict_rel = {}
    
    if rel in pos:
        for r in rel.split("_"):
            dict_rel[r] = {}
            for chr_type in ["autosome", "chrX"]:
                if r in parents:
                    dict_rel[r][chr_type] = dict_parents[r][chr_type]
                elif r in offs:
                    dict_rel[r][chr_type] = dict_off[chr_type]
    
    elif rel in sibs:
        for i, r in enumerate(rel.split("_")):
            r_new = r + str(i+1)
            dict_rel[r_new] = {}
            for chr_type in ["autosome", "chrX"]:
                if i == 0:
                    dict_rel[r_new][chr_type] = dict_off1[chr_type]
                else:
                    dict_rel[r_new][chr_type] = dict_off2[chr_type]
            
    return dict_rel

In [7]:
GenGeno = fgg.FamGenoSimul(num_variant, prop_commom_rare)
GenGeno

FamGenoSimul(num_variant=100, prop_common_rare=-1, maf_lim_common=[0.05, 0.95], maf_lim_rare=[0.01, 0.05], num_common=100, num_rare=0)

In [8]:
reltypes = [
    "father_son",
    "brother",
    "mother_daughter",
    "sister"
]

pos = [
    "father_son",
    "mother_daughter",
]

sibs = [
    "brother",
    "sister"
]

males = [
    "father_son",
    "brother",
]

females = [
    "mother_daughter",
    "sister"
]

In [9]:
# make phenotype

df_rel = pd.DataFrame(columns=["eid", "eid_rel", "pheno", "pheno_rel", "relation"])
idx = 100000
geno_r = {"autosome": pd.DataFrame(columns=np.arange(num_variant)),
          "chrX": pd.DataFrame(columns=np.arange(num_variant))}

for reltype in reltypes:
    # convert reltype appropriate for `famgen`
    if reltype == "brother":
        r = "son_son"
    elif reltype == "sister":
        r = "daughter_daughter"
    else:
        r = reltype
    
    # make genotype for given relationship
    rel_pair = make_family_geno(GenGeno, num_sample, r)
    geno_r[r] = rel_pair
    
    # make shared env
    s_fam = np.random.normal(0, 1, num_sample)
    s_relspec = np.random.normal(0, 1, num_sample) # s_po for po, s_sib for sib
    
    # make phenotype
    pheno_r = {}
    comps = ["autosome", "chrX", "fam", "po"] if r in pos else ["autosome", "chrX", "fam", "sib"]
    
    for rr in rel_pair.keys():
        pheno = np.zeros(num_sample)

        haps = rel_pair[rr]
        hsq_sum = 0
        for comp in comps:
            if comp == "autosome":
                pheno_comp = fgp.make_pheno(hsqs[comp], haps[comp], beta[comp])
                
            elif comp == "chrX":
                if rr in males:
                    pheno_comp = fgp.make_pheno(hsqs[comp], haps[comp], beta[comp])
                else:
                    pheno_comp = fgp.make_pheno(hsqs[comp], haps[comp], beta[comp], dc_type=dc_type)
            
            elif comp == "fam":
                pheno_comp = fgp.set_var(hsqs[comp], s_fam)
            
            else:
                pheno_comp = fgp.set_var(hsqs[comp], s_relspec)
            
            pheno += pheno_comp
            hsq_sum += hsqs[comp]
        
        e = np.random.normal(0, 1, num_sample)
        var_e = 1 - hsq_sum
        e = fgp.set_var(var_e, e)
        pheno += e
    
        pheno_r[rr] = pheno
    
    # make rel
    idx_m1 = np.arange(idx+1, idx + num_sample + 1)
    idx_m2 = np.arange(idx + num_sample + 1, idx + 2 * num_sample + 1)
    df_tmp = pd.DataFrame({"eid": idx_m1,
                           "eid_rel": idx_m2,
                           "pheno": pheno_r[list(pheno_r.keys())[0]],
                           "pheno_rel": pheno_r[list(pheno_r.keys())[1]],
                           "relation": reltype})
    idx += 2 * num_sample
    df_rel = pd.concat([df_rel, df_tmp], axis=0).reset_index(drop=True)
    
    # make genotype matrix
    dict_geno = {}
    for chrtype in ["autosome", "chrX"]:
        tmp_geno = pd.DataFrame()
        for ir, rr in enumerate(rel_pair.keys()):
            idx_id = idx_m1 if ir == 0 else idx_m2
            tt = pd.DataFrame(fgp.hap_to_geno(rel_pair[rr][chrtype]), 
                              index=idx_id)
            if (rr in ["father", "son"]) & (chrtype == "chrX"):
                tt = tt * 2
                
            tmp_geno = pd.concat([tmp_geno, tt], axis=0)
        dict_geno[chrtype] = tmp_geno

    for chrtype in ["autosome", "chrX"]:
        geno_r[chrtype] = pd.concat([geno_r[chrtype], dict_geno[chrtype]], axis=0)

In [10]:
df_pheno = pd.concat([df_rel[["eid", "pheno"]],
                      df_rel[["eid_rel", "pheno_rel"]].rename(columns={
                          "eid_rel": "eid",
                          "pheno_rel": "pheno"
                          })], axis=0).reset_index(drop=True)
df_pheno

        eid     pheno
0    100001  0.215042
1    100002 -0.277481
2    100003  0.643361
3    100004  0.096283
4    100005 -1.332811
..      ...       ...
795  100796  0.601846
796  100797  0.944064
797  100798  1.966602
798  100799 -3.445037
799  100800  0.103893

[800 rows x 2 columns]

In [11]:
# make eGRM
df_rels = df_rel[["eid", "eid_rel", "relation"]]
egrm_A = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                      columns=df_pheno["eid"].values,
                      index=df_pheno["eid"].values)

for i in range(df_rels.shape[0]):
    m1, m2, rel_type = df_rels.iloc[i, :]
    egrm_A.loc[m1, m2] = 1/2
    egrm_A.loc[m2, m1] = 1/2

egrm_fam = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                      columns=df_pheno["eid"].values,
                      index=df_pheno["eid"].values)

for i in range(df_rels.shape[0]):
    m1, m2, rel_type = df_rels.iloc[i, :]
    egrm_fam.loc[m1, m2] = 1
    egrm_fam.loc[m2, m1] = 1

egrm_po = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                      columns=df_pheno["eid"].values,
                      index=df_pheno["eid"].values)

for i in range(df_rels.shape[0]):
    m1, m2, rel_type = df_rels.iloc[i, :]
    if rel_type in pos:
        egrm_po.loc[m1, m2] = 1
        egrm_po.loc[m2, m1] = 1
        
egrm_sib = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                      columns=df_pheno["eid"].values,
                      index=df_pheno["eid"].values)

for i in range(df_rels.shape[0]):
    m1, m2, rel_type = df_rels.iloc[i, :]
    if rel_type in sibs:
        egrm_sib.loc[m1, m2] = 1
        egrm_sib.loc[m2, m1] = 1

In [12]:
grm = [egrm_A, egrm_fam, egrm_po, egrm_sib]
h0 = np.array([0.2, 0.2, 0.2, 0.2, 0.2])
pheno = df_pheno["pheno"]

gcta_fs = aiREML(grm, pheno, h0, max_iter=10, verbose = True)

Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-566.3553812630988 0.0001 1.7764561482044736
-2642.275112559984 0.0001 513.7764561482045
-5268.213497376925 0.0001 0.0001
-10350.207345476829 137438953472.0001 0.0001
-21930.644277242624 3.022314549037947e+23 0.0001
-45297.84580126101 1.7538019647970835e+49 0.0001
-91271.69556742565 0.0001 0.0001
nan nan nan

/home/jerrylee/miniconda3/envs/BIGFAM/lib/python3.9/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)

# real

In [13]:
df_dor = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/relative_information/relatives.formatted.info",
    sep='\t'
)
df_dor

,DOR,rcode,relationship,volid,relid,volage,relage,volsex,relsex,Erx
0,1,SB,daughter-sister,1000094,3653174,65,64,F,F,0.75
1,1,NaN,NaN,1000220,1691267,64,64,F,F,NaN
2,1,NaN,NaN,1000286,1571411,53,70,F,F,NaN
3,1,NaN,NaN,1000295,1045127,60,41,F,F,NaN
4,1,NaN,NaN,1000476,3599303,50,51,F,M,NaN
...,...,...,...,...,...,...,...,...,...,...
81321,3,1C,son-(father-brother)/(father-sister)-daughter,6023723,4863061,62,64,F,M,0.00
81322,3,NaN,NaN,6024211,1209127,53,60,M,F,NaN
81323,3,NaN,NaN,6024384,1854265,62,44,M,M,NaN
81324,3,1C,son-(father-sister)/(father-sister)/(mother-br...,6024486,3148753,58,56,M,M,0.00
81325,3,NaN,NaN,6024699,3556712,65,47,M,F,NaN

In [32]:
# 200 pairs for each DOR
df_under = df_dor.groupby("DOR").sample(300)
df_under

df_id = pd.DataFrame({
    "eid": list(set(df_under["volid"].unique()) | set(df_under["relid"].unique()))
})
df_id

          eid
0     5476353
1     4521987
2     2371589
3     2715654
4     5603333
...       ...
1787  3133425
1788  1806326
1789  5898233
1790  2465787
1791  2985983

[1792 rows x 1 columns]

In [33]:
pheno_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/phenotype"
pheno_fns = os.listdir(pheno_path)

In [34]:
df_res = pd.DataFrame(columns=["pheno", "error", "values"])

for ii, pheno_fn in enumerate(pheno_fns):
    pheno =  pheno_fn.split(".")[0]
    print(f"[{ii+1}/{len(pheno_fns)}] {pheno}")
    
    # phenotype
    df_pheno = pd.read_csv(f"{pheno_path}/{pheno_fn}",
                           sep='\t',)
    df_pheno = pd.merge(df_id, df_pheno[["eid", "pheno"]])
    
    df_rels = df_under[["volid", "relid", "DOR"]]
    df_rels = df_rels[(df_rels["volid"].isin(df_pheno["eid"])) & (df_rels["relid"].isin(df_pheno["eid"]))]
    
    # make eGRM
    egrm_A = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                        columns=df_pheno["eid"].values,
                        index=df_pheno["eid"].values)

    for i in range(df_rels.shape[0]):
        m1, m2, dor = df_rels.iloc[i, :]
        egrm_A.loc[m1, m2] = (1/2)**dor
        egrm_A.loc[m2, m1] = (1/2)**dor

    egrm_d1 = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                        columns=df_pheno["eid"].values,
                        index=df_pheno["eid"].values)

    for i in range(df_rels.shape[0]):
        m1, m2, dor = df_rels.iloc[i, :]
        if dor == 1:
            egrm_d1.loc[m1, m2] = 1
            egrm_d1.loc[m2, m1] = 1

    egrm_d2 = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                        columns=df_pheno["eid"].values,
                        index=df_pheno["eid"].values)

    for i in range(df_rels.shape[0]):
        m1, m2, dor = df_rels.iloc[i, :]
        if dor == 2:
            egrm_d2.loc[m1, m2] = 1
            egrm_d2.loc[m2, m1] = 1

    egrm_d3 = pd.DataFrame(np.eye(df_pheno.shape[0]).astype(int),
                        columns=df_pheno["eid"].values,
                        index=df_pheno["eid"].values)

    for i in range(df_rels.shape[0]):
        m1, m2, dor = df_rels.iloc[i, :]
        if dor == 3:
            egrm_d3.loc[m1, m2] = 1
            egrm_d3.loc[m2, m1] = 1

    try:
        grm = [egrm_A, egrm_d1, egrm_d2, egrm_d3]
        h0 = np.array([0.2, 0.2, 0.2, 0.2, 0.2])
        pheno_val = df_pheno["pheno"]

        gcta_fs = aiREML(grm, pheno_val, h0, max_iter=10, verbose = True)
        df_res.loc[len(df_res)] = [pheno, False, gcta_fs]
    except:
        df_res.loc[len(df_res)] = [pheno, True, None]

[1/106] White_blood_cell__leukocyte__count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1558.5047400422995 0.0001 2.5260193745654824
-4522.629584149958 0.0001 66.52601937456548
-8407.39999374194 16384.0001 0.0001
-18382.140889564707 0.0001 1073741824.0001
36177.179574026384 0.0001 0.0001
-70997.75197898233 7.875675875025626e+34 9.844594843782034e+34
-142588.03316041947 0.0001 2.7606985387162255e+70
-1393465.7058103352 0.0001 0.0001
-398113.93689369474 0.0001 0.0010765625
-411716.5460954413 0.0007171875 0.00045937500000000004
[2/106] Lymphocyte_count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
17.46083708049946 0.025663451348531104 0.09879688030270736
19.82381290335786 0.0861478263485311 0.07472656780270737
-921.5247341321639 0.0001 1.2523203178027074
-83819.60303896126 0.0001 0.0001
-167.8655176448915 0.21347890625 0.0001
-70.24590958452154 0.24310390625 0.0001
-10.53348214247012 0.0001 0.23709999999999998
15.130678645199055 0.0396 0.09884999999999997
-66.79468273997526 0.5926 0.0001
-142.44454373843138 0.5926 0.0001

/data/jerrylee/pjt/BIGFAM.v.0.1/BIGFAM/reml_utils.py:170: RuntimeWarning: invalid value encountered in sqrt
  return [np.sqrt(SE), Sinv]

[3/106] Trunk_fat-free_mass
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-835.712022374492 0.0001 0.32081237648110805
-986.8747111748023 0.0001 0.7997498764811081
-1057.0075208080002 0.0001 0.0001
-1244.7523421611954 2.5001 0.7501
-3644.8768701575677 66.5001 0.0001
-8338.094618208119 0.0001 8192.0001
-344733.67365876137 0.0001 0.0001
-31741.623766475357 0.0001 0.0001
-66487.54227047687 8.203829036485028e+32 0.0001
-133581.9963562303 1.2637475000226862e+66 0.0001
[4/106] Whole_body_water_mass
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-825.3712444961074 0.17284541684534538 0.19409706415714242
-843.5784597480824 0.0001 0.44837831415714247
-820.6091295468351 0.1251 0.26087831415714247
-820.0030565423641 0.03622499999999999 0.31025331415714247
-873.3198691291817 1.0831 0.0001
-1302.2111688531086 0.0001 1.7501
-2024.7405292212131 8.0001 0.0001
-3207.2077524185 40.0001 0.0001
-7086.414107251361 0.0001 2048.0001
-13119.654880778513 0.0001 0.0001
[5/106] HDL_cholesterol
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-705.2549083779203 0.4402573386484073 0.03848664418631831
-703.4338734195552 0.1387612448984073 0.1825999254363183
-710.8042880837833 0.7016362448984073 0.0001
-719.1628151788594 0.6391362448984073 0.0001
-866.9276626315143 1.5141362448984073 0.0001
-2930.1792938788453 41.51413624489841 0.0001
-8365.874453297989 16425.5141362449 16384.0001
-17100.0890395648 0.0001 1073758208.0001
-34996.76313221614 0.0001 4.611686019501146e+18
-70086.22864956553 2.5521177519070385e+38 0.0001
[6/106] Creatinine__enzymatic__in_urine
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-878.1174611152192 0.5197068258247689 0.0001
-872.0485678462784 0.2975193258247689 0.075396875
-904.2108422730516 0.7900349508247689 0.0001
-1740.8297975482128 6.790034950824769 0.0001
-4783.65328317274 262.79003495082475 0.0001
-9494.052861696971 0.0001 16384.0001
-284754.5106655972 0.0001 25769820160.0001
[7/106] Albumin
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-770.9299712687244 0.5057085789742795 0.0001
-989.8086979571889 2.0560835789742793 0.0001
-1085.1128431389072 0.0001 0.0001
682.440360900648 0.0001 4.0001
-906.508859737633 0.0001 0.0001
-800.4482288704666 0.7501 0.2501
-807.2112367883999 0.9476 0.022974999999999995
-804.9313789101739 0.3226 0.0001
-965.9038979868284 1.2706 0.0001
-2172.378817213109 15.2706 0.0001
[8/106] Body_mass_index__BMI_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-887.0086241864414 0.5715047613467465 0.0001
-887.8476492295611 0.7183953863467465 0.0001
-938.2245601762144 0.0001 0.484475
-1111.0536338099303 0.0001 0.921975
-945.1934542941981 0.0001 0.0001
-886.601291876611 0.0001 0.1186
-885.1624478512015 0.0445375 0.13094375
-884.417987193646 0.10872499999999999 0.12600625
-1536.6797334191824 0.0001 2.09475625
-3315.385593358668 40.0001 0.0001
[9/106] Haemoglobin_concentration
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-935.9282275499007 0.0001 0.422993187960155
-1679.9187687738458 6.0001 0.0001
-4025.759595314591 102.0001 0.0001
-8410.118047471338 16486.0001 0.0001
-19796.9467004075 0.0001 3758096384.0001
-39597.59135885116 0.0001 3758096384.0001
-78793.95332482939 1.361129467683754e+39 6.80564733841877e+38
-156626.1148292996 0.0001 0.0001
-313861.3233178975 0.0001 2.359774195669897e+156
[10/106] Testosterone
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-704.8934590163619 0.05232560254139387 0.1760861659747732
-699.4904344636268 0.07207560254139388 0.1205392909747732
-696.900478161821 0.07084122754139388 0.0909142909747732
-743.0649110949389 0.7028412275413939 0.0001
-1896.4147544580148 10.702841227541393 0.0001
-5301.532533613149 0.0001 512.0001
-10867.482508187319 786432.0001 0.0001
-21061.735091266295 786432.0001 0.0001
-43398.401498055035 9.066943647109719e+23 0.0001
-87839.07691007674 2.923003274661806e+48 0.0001
[11/106] Standing_height
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-925.6452946643738 1.6960663723832814 0.0001
-109.4158239116619 0.0001 0.2501
-989.0227612925355 0.85181875 0.18467812499999997
-184751.15704435605 0.0001 1.184678125
-857.5292887656566 0.0001 0.95958046875
-1047.610719472725 0.0001 1.31508046875
-3402.0592081241743 0.0001 9.31508046875
-185768.63653932733 0.0001 9.31508046875
-2806.3277506570103 10.034035546875 0.0001
-4487.076421591434 90.930035546875 40.448100000000004
[12/106] Arm_predicted_mass__left_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-838.609677882351 0.3583588421905429 0.1302232317294449
-836.332855415441 0.0003900921905429233 0.3129107317294449
-835.1396073079798 0.4422963421905429 0.1030669817294449
-834.6732325105429 0.37317134219054293 0.1376294817294449
-882.5472010515773 1.025515092190543 0.0001
-1558.4917603507424 0.0001 2.5001
-1380.7507948747852 0.0001 0.0001
-1920.8724841084918 0.0001 5.6880999999999995
-2907.9147048719356 0.0001 0.0001
-5693.996447695508 512.0001 128.0001
[13/106] Leg_fat_percentage__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-847.866078043926 0.0001 0.2943725480325128
-1010.0174563125963 0.0001 0.7486225480325128
-980.3873574042591 0.0001 0.4986225480325128
-1605.4103772231822 0.0001 2.710622548032513
-1290.6755223168398 0.0001 0.0001
-2068.4644218857366 10.1121 0.0001
-3260.274023366499 0.0001 0.0001
-6837.6085373539445 0.0001 1536.0001
-15370.047927632544 33554432.0001 0.0001
-13388.924918002083 0.0001 0.0001
[14/106] Waist_circumference
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-856.0728778035874 0.33101644128293173 0.11272304484134597
-853.6480451803884 0.08228987878293173 0.23153163859134596
-990.183912142121 1.5635398787829318 0.0001
-2014.176708795443 0.0001 2.0001
-2314.4745071884863 0.0001 0.0001
-4651.018388772028 128.0001 0.0001
-13073.654430770743 0.0001 1572864.0001
-30122.286070029746 0.0001 211106234105856.0
-64241.364955683224 1.5211807202738753e+31 0.0001
-129534.2116983426 0.0001 4.113761393303015e+62
[15/106] Whole_body_fat-free_mass
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-916.6644309637869 0.0001 0.6100100489421161
-1558.814552792773 0.0001 2.360010048942116
-3782.9359929058955 0.0001 34.360010048942115
-5556.456881656813 0.0001 34.360010048942115
-11324.207265278035 0.0001 131106.36001004896
-23265.167956378227 274877906944.0001 131106.36001004896
-47771.76169727028 4.533471823557608e+23 0.0001
-96585.58864926273 0.0001 4.1104733549931645e+47
-193218.47582019842 0.0001 1.3349918974505688e+95
-388328.61652585334 5.703050772027744e+191 2.851525386013872e+191
[16/106] Apolipoprotein_A
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-736.0834879943251 0.03375044713441189 0.23362957366100373
-767.4533579382472 0.0001 0.4048991049110037
-1246.9662462934389 4.0001 0.0001
-2207.0253904408573 12.0001 0.0001
-3953.8209679140914 0.0001 64.0001
-7410.750227877059 0.0001 0.0001
-15669.760820443624 0.0001 201326592.0001
-32334.5557946996 5.764607523034235e+17 201326592.0001
[17/106] Forced_expiratory_volume_in_1-second__FEV1__Z-score
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-776.4404322493046 0.26786935721664046 0.22268005636356544
-774.9744550392138 0.24811935721664047 0.24736755636356544
-774.3104411128757 0.14813498221664045 0.3078519313635654
-907.2903231505709 0.0001 0.9504300563635655
-1823.1927270850174 12.0001 0.0001
-4967.796562206392 1036.0001 0.0001
-9268.679630075201 263180.0001 0.0001
-19912.314636918658 0.0001 549755813888.0001
-40416.90136152683 2.4178516392292583e+24 0.0001
-82160.28009017333 3.507603929594167e+49 0.0001
[18/106] Leg_fat_mass__left_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-2426.7976793354323 0.0001 7.714384512712122
-3882.226158200053 0.0001 0.0001
-9068.048688232753 0.0001 24576.0001
-17294.410838148007 0.0001 0.0001
-35093.37638459278 0.0001 1.4411518807585587e+17
-70150.58473179118 2.076918743413931e+34 0.0001
-141943.89267481538 1.3803492693581128e+70 0.0001
-285119.21926460526 1.1432184632504854e+141 0.0001
[19/106] Glycated_haemoglobin__HbA1c_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1902.0299291617512 0.0001 4.003708000185014
-2123.02043348534 0.0001 0.0001
-4678.284613031894 192.0001 64.0001
-1844515.7985466812 0.0001 0.0001
-504726.90826981294 0.0001 0.000832421875
-124330.57804733884 0.0001 0.003301171875
-66405.90624733815 0.0001 0.005769921875
-28394.757968300673 0.0001 0.014410546875000001
-21835.47638563845 0.01738125 0.008238671875
-16023.30890872919 0.029725 0.0070042968750000005
[20/106] Leg_fat_mass__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1051.810656554767 2.0040410987373085 0.0001
-1660.5188499243193 0.0001 4.0001
-3100.1392521000894 24.0001 0.0001
-5698.368271223381 0.0001 1280.0001
-9922.781330788715 0.0001 0.0001
-19199.068190742768 1207959552.0001 2650800128.0001
-38109.70355525034 0.0001 0.0001
-76229.81691525351 0.0001 4.253529586511731e+37
-154617.30288379837 0.0001 1.628326254899759e+76
-309369.4615127944 8.379879956214123e+152 0.0001
[21/106] Mean_corpuscular_haemoglobin
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-937.7029126784576 0.0001 0.5708889225124667
-1619.1543298382092 0.0001 2.5708889225124665
-3411.4968847446353 0.0001 34.57088892251247
-7749.339815111463 0.0001 3106.5708889225125
-16425.264980114942 0.0001 67111970.57088892
-31963.681728246687 9007199254740992.0 0.0001
-65986.50632772855 8.112963841460668e+32 0.0001
[22/106] Forced_vital_capacity__FVC_,_Best_measure
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1318.5705234342959 6.180452357898118 0.0001
-3845.684457553963 0.0001 128.0001
-6138.505396744584 0.0001 0.0001
-14510.366497802552 1879048192.0001 0.0001
-1329748.6701412222 0.0001 0.0001
-527055.9811094672 0.0001 0.0001
-287498.9428704618 0.0001 0.0008714843750000001
-218227.19137161362 0.0001 0.0011800781250000001
-166423.67071365865 0.001334375 0.0008714843750000001
-120905.4817405409 0.0050375 0.0001
[23/106] Arm_fat_percentage__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-894.806601225585 0.9282920946174656 0.0001
-2133.4376104008034 10.928292094617465 0.0001
-3070.5791797731454 0.0001 0.0001
-6641.1545564291455 2048.0001 0.0001
-12275.078746359353 0.0001 0.0001
-24606.190387547005 0.0001 549755813888.0001
-49510.998592655014 0.0001 1.208925819615179e+24
-100644.76059203534 5.846006549323612e+49 1.208925819615179e+24
-202670.4664412741 0.0001 1.3123504348698072e+100
nan nan nan

/home/jerrylee/miniconda3/envs/BIGFAM/lib/python3.9/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)

[24/106] Glucose
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-834.4923209813139 0.24228777219163922 0.12733864007699291
-1014.810949812394 0.0001 0.848213640076993
-872.2347803316536 0.0001 0.0001
-877.6738183807606 0.0001 0.1976
-1214.064956262197 3.5001 0.0001
-1589.4635547234545 3.5001 0.0001
-3653.691587677595 0.0001 64.0001
-4997.544240126023 0.0001 0.0001
8436.08813073159 0.0001 131072.0001
-15876.89272840689 0.0001 0.0001
[25/106] High_light_scatter_reticulocyte_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-384.4660474528887 1.1921032720168678 0.0001
-654.4281287257201 0.6921032720168678 0.0001
-1198.1900261212597 2.692103272016868 1.0001
-3903.8774910892425 0.0001 33.0001
-9459.255289793366 65536.0001 0.0001
-18616.951457380273 65536.0001 0.0001
-39525.6218079402 1.1068046444225738e+20 0.0001
-79851.33200079124 2.1778071482940062e+40 0.0001
-158697.77985715153 0.0001 0.0001
-317102.93010832666 2.811821121589498e+160 0.0001
[26/106] Hip_circumference
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-941.8870360312527 1.0024258091871563 0.0001
-922.3006809902888 0.2524258091871563 0.0001
-957.1383237892844 0.0001 0.33585
-1438.1116732360663 4.0001 0.0001
-3166.9697630339606 32.0001 0.0001
-8379.578261257191 12320.0001 0.0001
-16019.156320165277 12320.0001 0.0001
-32628.404579268597 0.0001 4503599627370496.0
-64917.2772242214 0.0001 0.0001
-130657.68807616789 2.468256835981809e+63 0.0001
[27/106] Forced_expiratory_volume_in_1-second__FEV1_,_Best_measure
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-678.5993422897809 0.10759864301728388 0.27906807983099574
-677.2481888968209 0.09278614301728388 0.30375557983099577
-676.5952182728661 0.4310048930172839 0.14575557983099577
-1276.639578162077 5.681004893017284 0.0001
-1884.5421370522647 0.0001 0.0001
-5587.335203202099 0.0001 2048.0001
-12562.586289192453 100663296.0001 0.0001
-25458.0656687339 1.801439861014528e+16 0.0001
-49091.45591597905 1.801439861014528e+16 0.0001
-98928.09324508373 1.2341284179909045e+63 0.0001
[28/106] Mean_sphered_cell_volume
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-995.8427702261235 0.0001 0.7438195822952789
-4003.706976746672 112.0001 0.0001
-7974.718793323379 0.0001 4096.0001
-15402.987198423603 67108864.0001 0.0001
-30984.48357631867 0.0001 3377699720527872.0
-63481.61862992683 0.0001 8.112963841460668e+31
-126354.91228419651 0.0001 0.0001
-253713.6181916242 0.0001 2.599377838238264e+128
[29/106] Monocyte_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-886.4752219247445 0.0001 0.4234796495764902
-1730.9550349113088 0.0001 3.2984796495764903
-3624.2751988264104 64.0001 0.0001
-3624.2751988264104 64.0001 0.0001
[30/106] Impedance_of_leg__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-939.606424136421 0.0001 0.43676882511189585
-1291.8839766288347 2.6251 0.0001
-2596.9482615535276 18.6251 0.0001
-4775.06204152052 0.0001 512.0001
-6448.5588050646265 708.0001 0.0001
-13979.249017979697 0.0001 6291456.0001
-26523.63780963496 0.0001 0.0001
-55421.183980761845 0.0001 1.5474250491067253e+27
-111183.1432819003 0.0001 6.129982163463556e+54
-222932.08343828362 1.8788340662190666e+110 0.0001
[31/106] Immature_reticulocyte_fraction
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-726.0990583353217 0.16533379175010657 0.1493458454657206
-723.8364653148216 0.21100566675010657 0.1123145954657206
-722.7704519200513 0.4143689480001066 0.0001
-831.8564356942958 1.2031345730001066 0.0001
-939.4054086105472 0.0001 0.2501
-1446.4776992465318 4.0001 0.7501
-1659.6058497740323 0.0001 0.0001
-3853.583949682308 0.0001 64.0001
-7372.540638373138 0.0001 64.0001
-14562.010490075296 0.0001 25165888.0001
[32/106] Monocyte_count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-720.916911232549 0.31482577889175534 0.11926590060256008
-718.9034487201536 0.5222007788917553 0.027922150602560078
-716.5302092508688 0.2901382788917553 0.1612346506025601
-728.0365537596484 0.6950132788917553 0.0001
-1038.1091801159737 0.0001 1.1251
-2297.1852141209515 14.0001 0.0001
-8727.735216380766 14.0001 12288.0001
-18105.464329338847 1073741838.0001 0.0001
-36157.461482516315 0.0001 0.0001
-73583.15102586194 6.31383297997835e+36 0.0001
[33/106] Potassium_in_urine
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1150.8316914541965 0.0001 1.0814197318566072
-2038.1747485256549 8.0001 0.0001
-3254.8262551883104 0.0001 0.0001
-7298.3607396078505 5120.0001 0.0001
-7298.3607396078505 5120.0001 0.0001
[34/106] Alanine_aminotransferase
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-922.1171430425238 0.11559914012713488 0.17229471431669607
-960.1541520492462 0.0001 0.3895447143166961
-1022.190321256837 0.7501 0.0001
-1545.5728242307675 4.7501 0.0001
-2162.2133875038676 0.0001 0.0001
-4581.94597861142 0.0001 128.0001
-9645.082855203747 65536.0001 0.0001
-18510.420841453113 1073807360.0001 0.0001
37930.109080673414 0.0001 1.3835058055282164e+19
-74517.39890178922 0.0001 2.688230698675414e+37
[35/106] Red_blood_cell__erythrocyte__count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-848.314090494625 0.0001 0.2862806633195665
-846.9399583726756 0.430896875 0.05668691331956646
-1689.4033374658575 0.0001 2.8611869133195666
-3586.3137325989974 64.0001 0.0001
-1755830.4170078703 0.0001 0.0001
-742309.0022866803 0.00058828125 0.00016103515625
-387795.6787774049 0.00182265625 0.0001
-317533.7252435195 0.00213125 0.0001
-179669.0640143521 0.00429140625 0.0001
-97270.48484361742 0.00429140625 0.0019515625
[36/106] Platelet_count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-809.9094488431521 0.0001 0.4053940371837119
-1491.7177806678326 0.0001 2.405394037183712
-1624.948164260435 0.0001 0.0001
-8758.046400925983 24576.0001 0.0001
-19481.066192742048 4294991872.0001 0.0001
-38912.36591109783 1.8446744078004543e+19 0.0001
[37/106] Basophill_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-832.506023133294 0.8128352035703581 0.0001
-1470.0974604171345 0.0001 1.9376
-4770.153987745938 256.0001 0.0001
-9571.330963944798 33024.0001 0.0001
18553.911268640684 0.0001 0.0001
-35824.732698589534 0.0001 7.286463909115273e+17
-73920.11927230856 9.304595970494411e+36 0.0001
-147287.52045122455 0.0001 0.0001
-294488.770409145 0.0001 1.198751443321341e+147
[38/106] Lymphocyte_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1969.4509636586622 9.05523378315936 0.0001
-3622.9573410877592 41.05523378315936 0.0001
-324090.10483542917 0.0001 0.0001
-1362.9533233424136 0.0510033203125 0.0001
-1091.606276266559 0.1300033203125 0.0001
-943.3207969040388 0.2485033203125 0.0001
-905.27173906181 0.01150332031250001 0.1976
-941.9247368729926 0.0001 0.5136000000000001
-1121.6094653602133 1.5001 0.0001
-914.5142735492557 0.0001 0.0001
[39/106] Reticulocyte_count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-228.51285270656717 0.14646430923323955 0.07364375912218914
-224.69017423810624 0.19799946548323955 0.04926485287218914
-719.0529189418215 0.0001 0.7997648528721892
-1475.4252735847483 2.0001 0.0001
-4522.279542070711 0.0001 128.0001
-10244.97214683491 163840.0001 0.0001
-20094.202880076897 0.0001 0.0001
-41384.59731930538 2.9514790517935283e+20 5.902958103587057e+20
-82837.09563577891 0.0001 0.0001
-166841.91006689047 2.9140033383385936e+84 4.856672230564323e+83
[40/106] IGF-1
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-881.9792546404718 0.0001 0.3667145484686063
-2210.741707173376 13.0001 0.0001
-7291.503717451893 0.0001 2048.0001
-13789.279365095845 0.0001 0.0001
-27798.798105648017 0.0001 35184372088832.0
-54647.90035099194 0.0001 2.475880078570796e+27
[41/106] Mean_corpuscular_haemoglobin_concentration
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-721.5547387641392 0.31630984111784166 0.028657517318088244
-731.7114750954149 0.5928098411178417 0.0001
-3416.4569778178547 52.59280984111784 0.0001
-6318.8269895939775 0.0001 0.0001
-259240.42935407712 0.0001 0.0001
-5632.361252305567 0.0001 318.73203359375
-10123.76959651626 0.0001 83156.23603359376
-21090.281901290688 34359738368.0001 0.0001
-43003.4690568914 2.3611832414691823e+21 0.0001
-85779.04303583417 0.0001 0.0001
[42/106] Leg_predicted_mass__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-804.8705497488162 0.07107892865114798 0.24288965964411507
-1336.8621105254192 3.744578928651148 0.0001
-1420.939650394363 0.0001 0.0001
-3373.6226001193604 32.0001 0.0001
-9963.52713444863 90144.0001 0.0001
-21147.09694289084 30064861216.0001 0.0001
-43068.22721315957 0.0001 1.1805916207174113e+21
-87169.59296496058 1.393796574908164e+43 0.0001
-174872.56889130696 2.4866161820489332e+86 0.0001
-349959.2586847788 0.0001 3.091630018413807e+172
[43/106] Leg_fat_percentage__left_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-892.9843969858159 1.1782769688974644 0.0001
-1050.8740027317076 1.6782769688974644 0.0001
-1941.2579995892727 0.0001 0.0001
-2902.4370615432554 0.0001 0.0001
-6033.002472129063 1024.0001 0.0001
-17698.600325707674 603980800.0001 0.0001
-34184.07408561906 603980800.0001 0.0001
-69017.9091218783 0.0001 8.437482395119095e+33
-137734.296507305 0.0001 8.437482395119095e+33
-275695.46441782 0.0001 1.7444129383094565e+136
[44/106] Arm_fat-free_mass__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-859.5543186517075 0.0001 0.5296411568755387
-1740.7513253161637 0.0001 2.5296411568755386
-3082.6686465015982 0.0001 34.52964115687554
-7155.630480366853 0.0001 34.52964115687554
-251663.7319123633 0.0001 12582946.529641157
-45222.803646393935 0.0001 4.2410794544276844e+23
-97539.31561457412 1.9554184851714378e+41 0.0001
-197009.9960044069 2.990381850289274e+97 0.0001
-392283.5949632991 0.0001 0.0001
[45/106] Total_protein
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-760.2570228523048 0.946528887035179 0.0001
-847.956345277572 0.821528887035179 0.0001
-1269.949220977372 3.821528887035179 0.0001
-1718.5065190180364 0.0001 0.0001
-6955.2561758584625 0.0001 4096.0001
-13368.959344651767 0.0001 0.0001
-27598.098842331372 0.0001 844424930131968.0
-55853.80917298527 2.535301200456459e+30 0.0001
-112638.62052518899 5.142201741628769e+61 0.0001
-226777.091490071 1.5865343250965966e+124 0.0001
[46/106] Mean_reticulocyte_volume
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-817.370168084193 0.0001 0.2886379248047296
-814.1893212301858 0.009975 0.2540754248047296
-812.3902164409076 0.029725 0.2170441748047296
-811.8906111634009 0.12353750000000001 0.1602629248047296
-1100.4455547876644 0.0001 0.9571379248047296
-4116.848890219455 128.0001 0.0001
-8573.795474795412 16512.0001 0.0001
-323886.91593784187 0.0001 1610612736.0001
-323886.91593784187 0.0001 1610612736.0001
[47/106] Impedance_of_arm__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-880.0763103160597 0.8634291642940876 0.0001
-869.8329409550557 0.17592916429408756 0.109475
-952.9918404686686 1.0893666642940876 0.0001
-1986.9534124511015 9.089366664294088 0.0001
-3711.9097027334456 41.08936666429409 0.0001
-7511.321216294475 0.0001 3072.0001
-15726.981063892828 0.0001 25168896.0001
-32538.753792175354 1.3510798882111488e+16 0.0001
-64617.262750081805 0.0001 2.028240960365167e+31
-128216.79752944809 0.0001 8.22752278660603e+62
[48/106] Sodium_in_urine
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1040.6798033581053 0.0001 0.848714525727637
2478.098619747413 0.0001 0.848714525727637
-4218.438069268767 80.8961 0.0001
-8681.822255929172 20560.8961 0.0001
16740.008597302796 0.0001 0.0001
26824.221620007425 0.0001 1.4231374822490768e+16
[49/106] Mean_platelet__thrombocyte__volume
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-853.8774008200785 0.8117749333752251 0.0001
-927.3117373181619 1.436774933375225 0.0001
-3293.549384709444 45.436774933375226 0.0001
-8157.224333017041 12333.436774933376 0.0001
-15433.76160725682 33566765.43677493 0.0001
-30083.26812550824 0.0001 281474976710656.0
-59853.71282661606 0.0001 3.96140812571322e+29
-122324.6319752668 9.641628265553942e+60 0.0001
-1757809.1611463937 0.0001 0.0001
-319279.2009569672 0.0001 0.0001
[50/106] Lipoprotein_A
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1341.245080660883 6.004478197381128 0.0001
-2737.8735962985943 0.0001 32.0001
-6538.397638694462 0.0001 8224.0001
-13175.632104011396 134217728.0001 0.0001
-26951.6919031501 0.0001 3.602879701896397e+16
-53508.205365130045 0.0001 0.0001
106762.96708332007 4.2124916667422875e+65 9.478106250170147e+65
-212154.69879121552 0.0001 9.478106250170147e+65
[51/106] Arm_fat_percentage__left_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-940.0553311865615 0.0001 0.5380099319614584
-1248.7128791379587 0.0001 0.03800993196145841
-1401.583524611389 4.0001 0.0001
-2515.6092868003025 12.0001 0.0001
-2207.408713621278 12.0001 0.0001
-5226.011216256511 335.5841 80.8961
-11718.628528779709 0.0001 262224.8961
-25892.75755985256 0.0001 2748779331664.896
-54469.59334649646 0.0001 4.6422751473202035e+26
-108498.85169131085 0.0001 0.0001
[52/106] Arm_predicted_mass__right_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-812.5254251257227 0.0001 0.367078577356011
-828.9372763817073 0.6251 0.0001
-1241.4219475666353 0.0001 1.5001
-2240.984439784984 0.0001 3.5000999999999998
-241055.03455187578 0.0001 99.5001
-6187.477296461854 1027.68027578125 0.0001
-11414.948748502122 332377.69627578126 0.0001
-22434.14473114937 0.0001 68719476736.0001
-45366.16879216038 0.0001 4.722366482938365e+21
-90981.17063901611 1.0704357695294699e+45 0.0001
[53/106] Trunk_fat_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-2145.0105939670325 0.0001 5.329218181157235
-4884.200067677954 256.0001 0.0001
-9802.687947226312 65792.0001 0.0001
-20639.091786946232 0.0001 8589934592.0001
-40437.709933067395 0.0001 0.0001
-80887.84068158903 1.0889035741470031e+40 0.0001
-162142.50580470645 0.0001 0.0001
-324583.5713229502 0.0001 3.8662540421855594e+160
[54/106] Leg_predicted_mass__left_
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-807.9398370371147 0.8109445168516223 0.0001
-827.6940886809714 0.9294445168516223 0.0001
-1274.358915880773 2.929444516851622 0.0001
-5492.894228180933 0.0001 320.0001
-368881.1965984211 0.0001 0.0001
-801.269223368811 0.0001 0.21329580078125
-799.3890619000865 0.0001 0.25279580078124997
-965.7978141622123 1.4221 0.0001
-1396.5688461992345 0.0001 4.0001
-1950.3632791677528 0.0001 0.0001
[55/106] Apolipoprotein_B
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-877.6581243492799 0.0001 0.41716188554672357
-885.6190762772285 0.0001 0.0001
-867.7749636361339 0.0001 0.28135
-998.7244938906412 0.0001 0.67635
-2939.8885048446023 32.0001 0.0001
-6470.567934709901 0.0001 1536.0001
-14332.296810776978 0.0001 9384448.0001
-28954.059900410368 281474976710656.0 0.0001
-59351.5620787358 1.2676506002282297e+30 3.1691265005705735e+29
-117620.73456099369 0.0001 0.0001
[56/106] Urate
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1029.5710139814435 1.954749766076087 0.0001
-2761.430861364645 0.0001 12.0001
-5055.8350050769095 0.0001 140.0001
-296828.4438908053 0.0001 140.0001
-12403.391824788934 0.0001 239837.34385
-24548.242128770347 2779565395017.728 0.0001
-1802478.2372144933 0.0001 0.0001
-583451.2714153266 0.00058828125 0.00028310546875
-105605.80316060554 0.007994531249999999 0.0001
-92551.87254081208 0.007994531249999999 0.0001
[57/106] Vitamin_D
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1726.2775276468312 0.0001 3.5842186011586383
-3613.842467394722 64.0001 0.0001
-7317.265327223391 8256.0001 0.0001
-14308.989371213032 0.0001 16777216.0001
-28817.083850557803 2251799813685248.0 0.0001
-59002.827501083935 2.028240960365167e+31 0.0001
-117334.81400557923 0.0001 0.0001
-236161.596279412 0.0001 2.5384549201545546e+125
[58/106] Whole_body_fat_mass
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-865.2719839852494 0.0001 0.3121317616007394
-934.9275190987894 1.2641 0.0001
-874.4795839034626 0.0001 0.0001
-878.9946431928465 0.325975 0.0001
-948.8354587376866 0.0001 0.6876
-4113.3929417686095 0.0001 48.6876
-9677.384086810478 32768.0001 16432.6876
-9059.695757322737 32768.0001 0.0001
-17800.41199937219 0.0001 169651208.1921
-38289.81853739197 0.0001 5.764607523203886e+18
[59/106] Eosinophill_count
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-946.025366438125 0.0001 0.4826317404534184
-1018.2868613549957 0.0001 0.2326317404534184
-1079.297870274313 0.0001 0.9826317404534184
-1369.966959528157 2.0001 0.0001
-4523.924096294582 0.0001 128.0001
-9221.854753919652 0.0001 128.0001
-1867546.9297566514 0.0001 0.0001
-979740.2270597463 0.0001 0.00028310546875
-758794.8561069159 0.0007171875 0.0001
-925068.2261036132 0.00010000000000000005 0.000254296875
[60/106] Neutrophill_percentage
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-1097.0712121426577 2.144219214266837 0.0001
-1278.987247319676 0.0001 0.0001
-2783.458482629459 0.0001 24.0001
-4804.392750284822 0.0001 0.0001
-11926.748032967284 0.0001 655360.0001
-23715.967175633203 0.0001 0.0001
-1881030.2627467986 0.0001 0.0001
-1313490.323191282 0.0001 0.0001
-784357.4066573497 0.000562890625 0.0001
-607315.592594515 0.0007171875 0.00013857421875
[61/106] Triglycerides
Perform a single iteration of EM-based REML to initiate parameters
LogLike V(G) V(e)
Iterate AI REML until convergence
-834.6847868052706 0.00790934694771922 0.26942327995815857
-833.1459547550603 0.17084684694771923 0.16820452995815857
-1127.467022787356 0.0001 1.0618920299581585
-856.9913447819398 0.0001 0.06189202995815846

In [39]:
df_res[df_res["error"] == False]

,pheno,error,values
13,Whole_body_fat_mass,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
20,Red_blood_cell__erythrocyte__distribution_width,False,"[[1.7337875771562706e+106, 1.3070827984855963e..."
25,Townsend_deprivation_index_at_recruitment,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
46,Arm_fat-free_mass__left_,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
49,Whole_body_fat-free_mass,False,"[[1.3838256509620206e+88, 0.0001, 4.6705923953..."
54,MET_minutes_per_week_for_moderate_activity,False,"[[0.004235678940827401, 0.0032931351399160145,..."
55,Leg_predicted_mass__left_,False,"[[2.5357771281718143e+130, 0.0001, 0.0001, 0.0..."
63,Nucleated_red_blood_cell_count,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
65,Impedance_of_arm__left_,False,"[[6.40982242619366e+141, 4.747903422433448e+14..."
70,Body_fat_percentage,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
71,Arm_fat-free_mass__right_,False,"[[2.942596611490217e+157, 0.0001, 0.0001, 0.00..."
77,Forced_expiratory_volume_in_1-second__FEV1__Z-...,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
83,Arm_fat_mass__left_,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
87,Glycated_haemoglobin__HbA1c_,False,"[[1.1133138640215897e+82, 0.0001, 0.0001, 0.00..."
89,Hand_grip_strength__left_,False,"[[0.0001, 1.3797277431891116e+97, 1.1686773196..."
106,Mean_corpuscular_haemoglobin_concentration,False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
110,Trunk_fat_mass,False,"[[0.0001, 0.0001, 0.0001, 0.0001, 1.5540141907..."
113,"Heel_bone_mineral_density__BMD__T-score,_autom...",False,"[[nan, nan, nan, nan, nan], [nan, nan, nan, na..."
127,Impedance_of_whole_body,False,"[[0.0001, 0.0001, 0.0001, 0.0001, 1.8802818867..."