In [10]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import sys
import sys; sys.path.append("/data/jerrylee/pjt/BIGFAM.v.0.1")

from BIGFAM import obj2, tools
import importlib

In [11]:
source = "GS"

# Step 1. Load data

In [12]:
# load FR-reg
frreg_path = f"/data/jerrylee/pjt/BIGFAM.v.0.1/data/{source}/frreg/REL"
fns = os.listdir(frreg_path)
len(fns)

32

# Step 2. Estimate X

In [13]:
df = pd.DataFrame(
    columns=[
        "pheno", "lambda", "weight", 
        "Vx", "lower_Vx", "upper_Vx"
    ]
)

for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        for weight in range(-2, 9):
            df_x = obj2.estimateX(
                df_frreg,
                n_resample=100,
                regout_bin=["DOR"],
                alpha_dicts={"type": "lambda", "weight":weight},)
        
            df.loc[len(df)] = [
                pheno, df_x["lambda"].mean(), weight,
                np.median(df_x["X"]), np.percentile(df_x["X"], 2.5), 
                np.percentile(df_x["X"], 97.5)
            ]
    except:
        print(fn)

  0%|          | 0/32 [00:00<?, ?it/s]

[1/32] avg_dia

  3%|▎         | 1/32 [00:25<13:12, 25.57s/it]

[2/32] max_leg

  6%|▋         | 2/32 [00:51<13:00, 26.02s/it]

[3/32] avg_hr

  9%|▉         | 3/32 [01:18<12:39, 26.19s/it]

[4/32] avg_sys

 12%|█▎        | 4/32 [01:44<12:12, 26.15s/it]

[5/32] PR_interval

 16%|█▌        | 5/32 [02:10<11:41, 25.97s/it]

[6/32] Glucose

 19%|█▉        | 6/32 [02:36<11:17, 26.06s/it]

[7/32] HDL_cholesterol

 22%|██▏       | 7/32 [03:02<10:48, 25.96s/it]

[8/32] Total_cholesterol

 25%|██▌       | 8/32 [03:27<10:20, 25.84s/it]

[9/32] QT_interval

 28%|██▊       | 9/32 [03:53<09:53, 25.80s/it]

[10/32] Sodium

 31%|███▏      | 10/32 [04:19<09:27, 25.80s/it]

[11/32] FEV

 34%|███▍      | 11/32 [04:44<09:00, 25.76s/it]

[12/32] QRS_axis

 38%|███▊      | 12/32 [05:10<08:33, 25.66s/it]

[13/32] Heart_Rate

 41%|████      | 13/32 [05:35<08:07, 25.66s/it]

[14/32] max_arm

 44%|████▍     | 14/32 [06:01<07:42, 25.71s/it]

[15/32] ratio

 47%|████▋     | 15/32 [06:27<07:16, 25.67s/it]

[16/32] Creat_mgdl

 50%|█████     | 16/32 [06:52<06:50, 25.66s/it]

[17/32] max_sys

 53%|█████▎    | 17/32 [07:18<06:24, 25.64s/it]

[18/32] Potassium

 56%|█████▋    | 18/32 [07:44<05:58, 25.63s/it]

[19/32] FVC

 59%|█████▉    | 19/32 [08:09<05:33, 25.64s/it]

[20/32] abpi

 62%|██████▎   | 20/32 [08:39<05:22, 26.90s/it]

[21/32] FEF

 66%|██████▌   | 21/32 [09:05<04:51, 26.51s/it]

[22/32] ECG_Count

 69%|██████▉   | 22/32 [09:31<04:23, 26.34s/it]

[23/32] LVMI_Rautaharju

 72%|███████▏  | 23/32 [09:59<04:02, 26.90s/it]

[24/32] QRS_duration

 75%|███████▌  | 24/32 [10:26<03:36, 27.10s/it]

[25/32] T_axis

 78%|███████▊  | 25/32 [10:52<03:06, 26.63s/it]

[26/32] QTC_interval

 81%|████████▏ | 26/32 [11:19<02:40, 26.70s/it]

[27/32] Urea

 84%|████████▍ | 27/32 [11:44<02:11, 26.38s/it]

[28/32] P_duration

 88%|████████▊ | 28/32 [12:10<01:44, 26.17s/it]

[29/32] LVMI_Fhuwez

 91%|█████████ | 29/32 [12:38<01:19, 26.58s/it]

[30/32] Creatinine

 94%|█████████▍| 30/32 [13:03<00:52, 26.33s/it]

[31/32] expected

 97%|█████████▋| 31/32 [13:29<00:26, 26.16s/it]

[32/32] P_axis

100%|██████████| 32/32 [13:55<00:00, 26.11s/it]

In [ ]:
df_check = df[df["lower_Vx"] > 1e-6]
df_check["Vx/Vg"] = df_check["Vx"] / df_check["lambda"]
df_check

       pheno    lambda weight        Vx  lower_Vx  upper_Vx
0    avg_dia  0.271901     -2  0.090283  0.035008  0.147832
1    avg_dia  0.271901     -1  0.062060  0.026712  0.129288
2    avg_dia  0.271901      0  0.040185  0.011730  0.065499
3    avg_dia  0.271901      1  0.014438  0.003687  0.022051
4    avg_dia  0.271901      2  0.004312  0.001460  0.006886
..       ...       ...    ...       ...       ...       ...
181  max_sys  0.255924      3  0.001023  0.000409  0.001879
182  max_sys  0.255924      4  0.000269  0.000067  0.000448
183  max_sys  0.255924      5  0.000075  0.000021  0.000117
184  max_sys  0.255924      6  0.000017  0.000003  0.000032
185  max_sys  0.255924      7  0.000005  0.000002  0.000008

[63 rows x 6 columns]

In [ ]:
df_check = df[df["lower_Vx"] > 1e-6].groupby("weight").mean()
df_check["Vx/Vg"] = df_check["Vx"] / df_check["lambda"]
df_check.round(3)

        lambda     Vx  lower_Vx  upper_Vx  Vx/Vg
weight
-2       0.515  0.010    -0.038     0.057  0.019
-1       0.515  0.009    -0.031     0.048  0.017
 0       0.515  0.005    -0.021     0.031  0.010
 1       0.515  0.003    -0.012     0.020  0.006
 2       0.515  0.002    -0.009     0.014  0.005
 3       0.515  0.003    -0.009     0.015  0.006
 4       0.515  0.003    -0.009     0.016  0.006
 5       0.515  0.004    -0.009     0.017  0.008
 6       0.515  0.004    -0.010     0.018  0.008
 7       0.515  0.006    -0.009     0.020  0.011
 8       0.515  0.005    -0.010     0.022  0.010

# Step 3. Estimate XmXf

In [4]:
df = pd.DataFrame(
    columns=[
        "pheno", "lambda", "weight", 
        "Vx_male", "lower_Vx_male", "upper_Vx_male",
        "Vx_female", "lower_Vx_female", "upper_Vx_female",
        "r", "lower_r", "upper_r",
    ]
)

for ii, fn in enumerate(tqdm(fns)):
    pheno = fn.split(".")[0]
    print(f"[{ii+1}/{len(fns)}] {pheno}")
    
    # load FR-reg results
    df_frreg = pd.read_csv(f"{frreg_path}/{fn}", 
                           delim_whitespace=True)
    try:
        for weight in range(-2, 9):
            df_x = obj2.estimateXmXfR(
                df_frreg,
                n_resample=100,
                regout_bin=["DOR", "sex_type"],
                alpha_dicts={"type": "lambda", "weight":weight},)
            
            df.loc[len(df)] = [
                pheno, df_x["lambda"].mean(), weight,
                np.median(df_x["Xmale"]), np.percentile(df_x["Xmale"], 2.5), 
                np.percentile(df_x["Xmale"], 97.5),
                np.median(df_x["Xfemale"]), np.percentile(df_x["Xfemale"], 2.5), 
                np.percentile(df_x["Xfemale"], 97.5),
                np.median(df_x["r"]), np.percentile(df_x["r"], 2.5), 
                np.percentile(df_x["r"], 97.5),
            ]
    except:
        print(fn)

  0%|          | 0/32 [00:00<?, ?it/s]

[1/32] avg_dia

  0%|          | 0/32 [01:01<?, ?it/s]

In [9]:
df

,pheno,lambda,weight,Vx_male,lower_Vx_male,upper_Vx_male,Vx_female,lower_Vx_female,upper_Vx_female,r,lower_r,upper_r
0,avg_dia,0.271901,-2,0.294085,0.210913,0.351298,0.106977,0.032429,0.203574,-0.2,-1.0,0.6